name: my-ci-cd

# events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # permite startar manualmente
  workflow_dispatch:

jobs:
  continuous-integration-full:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repo
      - uses: actions/checkout@v2
      
      # Build na imagem
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: luizgustavoob/rotten-potatoes:v${{ github.run_number }}
